# Configuração do build para Netlify
[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

# Configurações de plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuração para SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações de cabeçalhos
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"
    X-Content-Type-Options = "nosniff"
