# Configuração do build para Netlify
[build]
  command = "npm run build"  # Usar build padrão do Next.js em vez da versão estática
  publish = ".next"          # Publicar a pasta .next em vez de out
  functions = "netlify/functions"

# Configurações de plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configurações de redirecionamento
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

# Configurações de cabeçalhos
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"
    X-Content-Type-Options = "nosniff"
