[build]
  command = "npm run build"
  publish = ".next"
  environment = { 
    NODE_VERSION = "18.20.8",
    MONGODB_URI = "mongodb://geneziodelavor:FbC38pTH2g9Kln6D@cluster0-shard-00-00.ozrtc.mongodb.net:27017,cluster0-shard-00-01.ozrtc.mongodb.net:27017,cluster0-shard-00-02.ozrtc.mongodb.net:27017/?replicaSet=atlas-ez3inn-shard-0&ssl=true&authSource=admin&retryWrites=true&w=majority&appName=Cluster0",
    MONGODB_CONNECT_TIMEOUT = "30000",
    MONGODB_SOCKET_TIMEOUT = "75000"
  }

[functions]
  external_node_modules = ["mongodb"]
  included_files = ["lib/**"]
  node_bundler = "esbuild"

[functions."api/*"]
  external_node_modules = ["mongodb", "mongoose"]
  included_files = ["lib/**", "models/**"]

[functions."next_api/*"]
  external_node_modules = ["mongodb", "mongoose"]
  included_files = ["lib/**", "models/**", ".env.local"]

[[redirects]]
  from = "/*"
  to = "/.netlify/builders/___netlify-handler"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs" 