# Configuração do build para Netlify
[build]
  command = "npm run build:static"
  publish = "out"

# Configurações de plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configurações de redirecionamento
[[redirects]]
  from = "/leaderboard"
  to = "/leaderboard.html"
  status = 200
  force = false

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Configurações de cabeçalhos
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors 'none'"
    X-Content-Type-Options = "nosniff"
