# Configuração básica do Netlify 
[build] 
  command = "npm run build" 
  publish = ".next" 
 
[build.environment] 
  NODE_VERSION = "18.20.8" 
  # Não defina MONGODB_URI aqui - use as variáveis de ambiente do Netlify
  # Configurações adicionais para tempos limite MongoDB
  MONGODB_CONNECT_TIMEOUT = "30000" 
  MONGODB_SOCKET_TIMEOUT = "75000" 
 
[[plugins]] 
  package = "@netlify/plugin-nextjs" 
